---
# A good template to model after for a Pythonic action
# https://github.com/akaihola/darker/blob/master/action.yml
name: Poetry (PyTOML) Github Tag
description: Gets the version from the PyTOML file and creates a Github Tag
author: Philip De Lorenzo

branding:
  # The icon to display for the workflow
  # https://github.com/haya14busa/github-action-brandings
  icon: battery-charging

outputs:
  version:
    description: The version from the PyTOML file
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.6

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install pytoml
      shell: bash

    - name: Get PyTOML Version
      id: get-version
      run: |
        #!/bin/bash
        ls -als ${{ github.workspace }}
        ls -als ${{ github.action_path }}
        echo "Getting version from PyTOML file"
        if [[ ! -f "${{ github.workspace }}/pyproject.toml" ]]; then
          echo "PyTOML file not found!"
          exit 1
        fi
        version=$(python -c "import pytoml; print(pytoml.load('pyproject.toml')['tool']['poetry']['version'])")
        echo "Version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash
